### ISSUE TITLE
GUI buttons do not function correctly while using aero glass.

### ISSUE THREAD

**Issue by OleExploder** [florinsdistortedvision/silverfox#15]
![Capture](https://github.com/florinsdistortedvision/silverfox/assets/113773450/8de2ca4c-efc7-4c1e-b2ab-014c29a6bd0d)
I am using Windows 10 22H2 with DWMBlurGlass for my Windows 7 aero theme and when I hover over a GUI button like the close button for example, the aero buttons do not light up and the GUI buttons behind them light up instead. I will say that already mentioned this in the Discord server but I created this issue in case you did not see it.

**Comment by florinsdistortedvision** [comment]
This is a known issue, its because I wanted to utilize the native Windows 10/11 mode, and not force Windows 7 mode (for future proofing). As a result the titlebar buttons remain the themed ones but had no hover, so i just did those as a hacky workaround. Not ideal, but I'll see how to handle this in the future.

**Comment by OleExploder** [comment]
Ok, thanks.
